### ISSUE TITLE
Update README with usage examples

### ISSUE THREAD

**Issue by dayyass** [yjs1224/TextSteganalysis#2]
Hi!
I read your articles and found some methods that I would be interested in trying on my tasks. But the README does not contain examples of using the repository and scripts.
Is it possible to add examples of running scripts and their purpose (since there are a lot of them)?

P.S. Would like to try using fcn model.

**Comment by yjs1224** [comment]
Thanks for your interest in this work. We will add some examples. For your try, **make a new config file** as "./configs/test.json" does, and then use this command: 

### python main.py --config_path your_config_path.


PS: You can find the  hyper-parameters of several method in the **./configs/test.json** . And if you would like to use pretrained language model like BERT for embedding words, please set **"use_plm: true"**, otherwise, set **“use_plm: false”**.

**Comment by yjs1224** [comment]
And to use fcn,  just set the "model" as fcn. And for your own data, change some parameters in the "Training_with_Processer" or "Training". Also, you can try your own hyper-parameters for fcn in "FCN" .

**Comment by dayyass** [comment]
Thanks for the quick response, I'll go try it out!
